version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: llm_extractor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d llm_extractor"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/llm_extractor
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.api:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data: